name: Java Build & Test

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Show folder contents
        working-directory: "./Folder Java"
        run: ls -l


      # ✅ Set working directory instead of using cd
      - name: Build
        working-directory: "./Folder Java"
        run: javac Barang.java Main.java

      - name: Run test
        working-directory: "./Folder Java"
        run: |
          java Main < tests/input.txt > output.txt
          diff -u tests/expected.txt output.txt
