name: Python Build & Test

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 3️⃣ Install dependencies (if you have a requirements.txt inside Folder Python)
      - name: Install dependencies
        run: |
          if [ -f "Folder Python/requirements.txt" ]; then
            pip install -r "Folder Python/requirements.txt"
          fi

      # 4️⃣ Run the program with test input and capture output
      - name: Run test
        run: |
          python "Folder Python/main.py" < "Folder Python/tests/input.txt" > "Folder Python/output.txt"
          diff -u "Folder Python/tests/expected.txt" "Folder Python/output.txt"
